// dsh-budget-handoff — a lifecycle/event plugin (generated by create-dsh-plugin).
//
// Unlike the `tool` template, this one has ZERO runtime dependencies: it only
// uses the `ctx` the host hands it, and every type import below is erased at
// compile time (`import type`), so nothing is imported at runtime.
//
// 空类型 import：触发 @deepseek-ai/dsh-agent 对 cordis `Events` 接口的声明合并，
// 让 ctx.on('agent/pre-step', ...) 能通过类型检查。不要删。
// （v0.1.1 删掉 tools/pre-execute 处理器后，原本靠 dsh-tools 传递进来的声明链断了。）
import type {} from '@deepseek-ai/dsh-agent'
import type { Context } from '@deepseek-ai/cordis'
import type { Session, SessionEvent } from '@deepseek-ai/dsh-session'
import z from '@deepseek-ai/schemastery'
import { Ledger } from './ledger.js'
import { calculateCost, isPeakHour } from './pricing.js'
import { buildSnapshot, writeSnapshot, writeSnapshotToDshHome } from './snapshot.js'

// 自定义消息来源 kind：`MessageSourceMap` 是 merge-extensible 接口，各生产者自声明。
// 写法依据（见 P2.2 实验）：dsh-time-context\lib\types\index.d.ts:10-17（~25 个内置包同形）。
import type { ContextFormed } from '@deepseek-ai/dsh-llm'
import { createUserMessage } from '@deepseek-ai/dsh-llm'

declare module '@deepseek-ai/dsh-llm' {
  interface MessageSourceMap {
    'budget-handoff': { kind: 'budget-handoff' } & ContextFormed
  }
}

// ── Config schema (schemastery) ──────────────────────────────────────────────
// DSH 的插件配置机制：本模块额外导出 `Config`，cordis 装载插件时用它校验配置并回填
// 默认值，解析后的对象作为 `apply(ctx, config)` 的第二个参数交给插件。
// 写法依据（见 A-1 取证）：dsh-provider-usage\lib\index.js:1/:711/:1869，以及内置插件
// dsh-time-context\lib\types\index.d.ts:8/:43/:50（~120 个内置插件同形）。
export interface Config {
  /**
   * 每会话预算，单位：人民币元（默认 1.0）。
   * 必须为正数；下限 0.0001 是展示精度（toFixed(4)）能表达的最小非零值。
   * 覆盖方式：profile 的 cordis.patch.yml 里该插件条目下写 `config: { budgetCNY: 2.5 }`。
   */
  budgetCNY: number
  /**
   * 价格表路径（默认 ''，表示用内置的 ./pricing.json）。
   * 本阶段只声明字段、不实现读取逻辑，留作将来扩展。
   */
  priceTablePath: string
}

export const Config: z<Config> = z.object({
  budgetCNY: z.number().min(0.0001).default(1.0),
  priceTablePath: z.string().default(''),
})

// Plugin display name, shown in loader diagnostics.
export const name = 'dsh-budget-handoff'

// ── Recent-event ring buffer for the hand-off snapshot ───────────────────────
/** 每个会话最多保留的事件摘要条数（与 snapshot.ts 的 MAX_RECENT_EVENTS 一致）。 */
const MAX_RECENT_EVENTS = 10

/**
 * 把一条会话事件压成一行短摘要；不关心的事件返回 null。
 *
 * 字段名全部实测查证（不靠猜）：
 * - `@deepseek-ai/dsh-session\lib\types\types.d.ts:255-388`：`step/end{turn,step}`、
 *   `tool/call{turn,step,callId,name,arguments}`、`tool/result{turn,step,message,error?}`
 *   （**没有** name/isError 顶层字段）、`assistant/message{…,usage?:TokenUsage}`、
 *   `turn/start{turn}`、`turn/end{turn,reason}`。
 * - `@deepseek-ai/dsh-llm\lib\types\message.d.ts:153-160`：`ToolResultMessage` 上才有
 *   `toolCallId` 与 `isError?`（工具名不在结果消息里，故用 callId 关联）。
 * - `@deepseek-ai/dsh-llm\lib\types\types.d.ts:160-174`：`TokenUsage.totalTokens?` 可选。
 */
function summarizeEvent(event: SessionEvent): string | null {
  switch (event.type) {
    case 'step/end':
      return `step/end turn=${event.data.turn} step=${event.data.step}`
    case 'tool/call':
      return `tool/call name=${event.data.name}`
    case 'tool/result':
      return `tool/result callId=${event.data.message.toolCallId} isError=${event.data.message.isError ?? false}`
    case 'assistant/message':
      return `assistant/message total=${event.data.usage?.totalTokens ?? '?'} tokens`
    case 'turn/start':
      return `turn/start turn=${event.data.turn}`
    case 'turn/end':
      return `turn/end reason=${event.data.reason?.kind ?? '?'}`
    default:
      return null
  }
}

export function apply(ctx: Context, config: Config) {
  // Cumulative token accounting, one record per session.
  const ledger = new Ledger()

  // Cumulative CNY spend, one total per session.
  const sessionCosts = new Map<string, number>()

  // 每会话的最近事件摘要（环缓冲），供交接快照的 recentEvents 使用。
  const recentEventsBySession = new Map<string, string[]>()

  // ① Durable session firehose (emit): fires whenever a session's log grows —
  //    turn/step boundaries, user/assistant messages, tool results, …
  ctx.on('session/event', (session: Session, event: SessionEvent) => {
    // 最近事件环缓冲：放在任何分支之前，保证每条事件都被记录。
    const sessionId = String(session.id)
    const summary = summarizeEvent(event)
    if (summary !== null) {
      const arr = recentEventsBySession.get(sessionId) ?? []
      arr.push(summary)
      while (arr.length > MAX_RECENT_EVENTS) arr.shift()
      recentEventsBySession.set(sessionId, arr)
    }

    // Token accounting. `SessionEvent` nests its payload under `data`
    // (`@deepseek-ai/dsh-session`, `lib/types/types.d.ts:489-512`:
    // `{ type: K; seq; time; data: SessionEventMap[K]; … }`), so the
    // `assistant/message` fields live at `event.data.message` / `event.data.usage`.
    if (event.type === 'assistant/message') {
      const payload = event.data
      const usage = payload.usage
      if (usage === undefined) {
        console.log('[dsh-budget-handoff] assistant/message without usage, skipped')
      } else {
        const provider = payload.message.source.provider
        const model = payload.message.source.model
        // Per-call billed total, derived from the four disjoint buckets
        // (`TokenUsage` upstream counts them disjointly).
        const callTotal =
          usage.inputTokens +
          (usage.cacheReadTokens ?? 0) +
          (usage.cacheWriteTokens ?? 0) +
          usage.outputTokens
        ledger.record(String(session.id), provider, model, usage)
        // `totalTokens` 是 TokenUsage 的可选字段（dsh-llm\lib\types\types.d.ts:170），
        // provider 未提供时回退到四桶求和 callTotal，保证这一行总有数字。
        console.log(
          `[dsh-budget-handoff] usage provider=${provider} model=${model} total=${usage.totalTokens ?? callTotal} tokens`,
        )

        // Money layer: price this call against the peak/off-peak table and fold
        // it into the session's running CNY total.
        const isPeak = isPeakHour(new Date())
        const cost = calculateCost(provider, model, usage, isPeak)
        if (cost >= 0) {
          const cumulativeCost = (sessionCosts.get(String(session.id)) ?? 0) + cost
          sessionCosts.set(String(session.id), cumulativeCost)
          console.log(
            `[dsh-budget-handoff] cost thisCall=${cost.toFixed(4)} 累计=${cumulativeCost.toFixed(4)} 元`,
          )
        } else {
          console.error(
            `[dsh-budget-handoff] ⚠️ 未知 provider/model: ${provider}/${model} — 本插件无法为其计费，预算保护已失效`,
          )
          console.error(
            `[dsh-budget-handoff]    如果你在用自定义 provider 或新模型，请更新 src/pricing.json 或换用已知模型`,
          )
        }
      }
    }
  })

  // ④ Budget gate (waterfall): the last line of defence before a step is
  //    proposed to the model. NOT calling next() short-circuits the loop, so
  //    returning `{ kind: 'reject' }` ends the turn with reason `blocked`
  //    instead of throwing, and no further request is billed.
  ctx.on('agent/pre-step', async (payload, next) => {
    const sessionId = String(payload.agent.session?.id ?? '')
    const spent = sessionCosts.get(sessionId) ?? 0
    if (spent >= config.budgetCNY) {
      const snapshot = buildSnapshot({
        sessionId,
        turn: payload.turn,
        step: payload.step,
        spentCNY: spent,
        budgetCNY: config.budgetCNY,
        reason: `session spent ${spent.toFixed(4)} CNY >= budget ${config.budgetCNY.toFixed(4)} CNY`,
        recentEvents: recentEventsBySession.get(sessionId) ?? [],
      })
      try {
        const noticeText = [
          `⛔ 预算已耗尽，任务已停止`,
          `累计消费：${spent.toFixed(4)} 元 / 预算：${config.budgetCNY.toFixed(4)} 元`,
          `交接快照已写入：`,
          `  1. ${process.cwd()}\\BUDGET-STOPPED-handoff-snapshot.md`,
          `  2. $DSH_HOME/storages/dsh-budget-handoff/last-stop.md`,
          `请查看快照了解任务进度，调整预算后重试。`,
        ].join('\n')
        const noticeMsg = createUserMessage({
          content: [{ type: 'text', text: noticeText }],
          source: {
            kind: 'budget-handoff',
            form: 'notice',
            summary: `预算耗尽：${spent.toFixed(4)}/${config.budgetCNY.toFixed(4)} 元`,
          },
        })
        payload.agent.session.append('user/message', noticeMsg, { surfaceOp: 'append' })
        console.log(`[dsh-budget-handoff] notice appended to session log`)
      } catch (err) {
        console.error(`[dsh-budget-handoff] failed to append notice: ${String(err)}`)
      }
      const workdirPath = writeSnapshot(snapshot, process.cwd())
      const dshHomePath = writeSnapshotToDshHome(snapshot)
      console.error(`[dsh-budget-handoff] ⛔ 预算已耗尽，任务已停止`)
      console.error(`[dsh-budget-handoff] 累计消费：${spent.toFixed(4)} 元 / 预算：${config.budgetCNY.toFixed(4)} 元`)
      console.error(`[dsh-budget-handoff] 交接快照已写入：`)
      console.error(`[dsh-budget-handoff]   1. ${workdirPath}`)
      console.error(`[dsh-budget-handoff]   2. ${dshHomePath}`)
      console.error(`[dsh-budget-handoff] 请查看快照了解任务进度，调整预算后重试。`)
      return { kind: 'reject' }
    }
    return next()
  })

  // ⑤ ctx.on() is already an EFFECT (auto-disposed on unload). The 30s heartbeat
  //    timer was removed in v0.1.1 (pure noise); this empty effect is kept only
  //    so the reversible-cleanup proof — the DISPOSED line on unload — survives.
  ctx.effect(() => {
    return () => {
      console.log(`[dsh-budget-handoff] DISPOSED — listeners removed`)
    }
  })

  console.log(`[dsh-budget-handoff] 已加载，预算 ${config.budgetCNY} CNY`)
}
